apiVersion: v1
kind: Service
metadata:
  name: hotel-accommodation-provider
  labels:
    app: hotel-accommodation-provider
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hotel-accommodation-provider