server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: user
          uri: http://localhost:8082
          predicates:
            - Path=, 
        - id: hotel-accommodation-provider
          uri: http://localhost:8083
          predicates:
            - Path=/hotels/**, 
        - id: airline
          uri: http://localhost:8084
          predicates:
            - Path=/flights/**, 
        - id: transportation-provider
          uri: http://localhost:8085
          predicates:
            - Path=/transportation/**, 
        - id: tourist-attraction-provider
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user:8080
          predicates:
            - Path=, 
        - id: hotel-accommodation-provider
          uri: http://hotelAccommodationProvider:8080
          predicates:
            - Path=/hotels/**, 
        - id: airline
          uri: http://airline:8080
          predicates:
            - Path=/flights/**, 
        - id: transportation-provider
          uri: http://transportationProvider:8080
          predicates:
            - Path=/transportation/**, 
        - id: tourist-attraction-provider
          uri: http://touristAttractionProvider:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
