apiVersion: v1
kind: Service
metadata:
  name: tourist-attraction-provider
  labels:
    app: tourist-attraction-provider
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: tourist-attraction-provider