apiVersion: apps/v1
kind: Deployment
metadata:
  name: transportation-provider
  labels:
    app: transportation-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transportation-provider
  template:
    metadata:
      labels:
        app: transportation-provider
    spec:
      containers:
        - name: transportation-provider
          image: "username/transportation-provider:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
