apiVersion: v1
kind: Service
metadata:
  name: transportation-provider
  labels:
    app: transportation-provider
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: transportation-provider